---
# Install CFME dependent packages

- name: cfme_install | install ansible dependencies (setsebool module)
  yum: name=$item state=present
  with_items:
    - libselinux-python
    - libsemanage-python

- name: cfme_install | install runtime dependencies
  yum: name=$item state=present
  with_items:
   - gcc-c++
   - patch
   - readline.x86_64
   - readline-devel.x86_64
   - zlib
   - zlib-devel.x86_64
   - libyaml-devel
   - libffi-devel
   - openssl-devel.x86_64
   - make
   - bzip2
   - autoconf
   - automake
   - libtool
   - bison
   - ruby-devel
   - freetds-devel
   - libxml2-devel.x86_64
   - libxslt-devel.x86_64
   - memcached
   - postgresql-server
   - postgresql-devel
   - net-tools
   - screen
  notify:
   - restart memcached

- name: cfme_install | install httpd dependencies
  yum: name=$item state=present
  with_items:
   - httpd
   - mod_ssl
  when: with_httpd

# First, attempt a shallow (depth=1) clone of cfme
- name: cfme_install | git clone --depth=1 {{cfme_src}}
  git: repo={{cfme_src}} version={{cfme_src_branch}} dest={{cfme_dir}} depth=1
  ignore_errors: true
  register: git_clone

# If the shallow copy failed (refer to
# https://github.com/ansible/ansible/pull/3578), clone the full repository.
# Note, it is a large repository and this may take a long time.
- name: cfme_install | git clone {{cfme_src}}
  git: repo={{cfme_src}} version={{cfme_src_branch}} dest={{cfme_dir}}
  when: git_clone|failed
