---
# Install CFME dependent packages

- name: cfme_install | install ansible dependencies (setsebool module)
  yum: name=$item state=present
  with_items:
    - libselinux-python
    - libsemanage-python

- name: cfme_install | install runtime dependencies
  yum: name=$item state=present
  with_items:
   - gcc-c++
   - patch
   - readline.x86_64
   - readline-devel.x86_64
   - zlib
   - zlib-devel.x86_64
   - libyaml-devel
   - libffi-devel
   - openssl-devel.x86_64
   - make
   - bzip2
   - autoconf
   - automake
   - libtool
   - bison
   - ruby-devel
   - freetds-devel
   - libxml2-devel.x86_64
   - libxslt-devel.x86_64
   - memcached
   - postgresql-server
   - postgresql-devel
   - net-tools
   - screen
  notify:
   - restart memcached

#
# Shallow (depth=1) clone cfme.git
#
- name: cfme_install | clone cfme.git
  git: repo=$cfme_src dest=$cfme_dir depth=1

- name: cfme_install | download vddk install script
  action: copy src=files/install_vddk.sh dest=$ENV(HOME)/install_vddk.sh mode=0755
